### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by cormacmchale** [cormacmchale/MobileGameProject#12]
Game will have to be configured with sound

**Comment by cormacmchale** [comment]
Will have to wait to here from designer about sound assets
https://github.com/cormacmchale/MobileGameProject/issues/7

**Comment by cormacmchale** [comment]
As long as it suits the developer I can get the basic sounds needed online to meet the Games requirements

**Comment by Liam-Higgins2018** [comment]
thats sound

**Comment by cormacmchale** [comment]
Starting here looking for sounds.
https://opengameart.org/content/car-engine-start-up-02

**Comment by cormacmchale** [comment]
https://opengameart.org/art-search?keys=Driving+sounds

**Comment by cormacmchale** [comment]
Audio Manager Implemented as a singleton with methods to play sound. Audio Menu implements a slider to change volume but at the moment its rests volume when it leaves the pause menu from the main game screen.

**Comment by cormacmchale** [comment]
For adding a toggle for sfx
https://www.youtube.com/watch?v=HhB-vTEZtg4

**Comment by cormacmchale** [comment]
AudioManager is implemented as a singleton and persists across all scenes. When it arrives on the Audio menu it has sfx set to true for playing sounds and the volume of the background music set to 1.0. So all sounds are turned on to full by default. The toggle and the slider on audio menu are then used to change the values on AudioManager to change the volume of the sounds. AudioManager then saves the new values so when you re-visit Audio menu the same values are preserved from before.

**Comment by cormacmchale** [comment]
![Capture3](https://user-images.githubusercontent.com/33293951/69727767-0db55c00-111b-11ea-8923-5ce9acb22d90.PNG)
![Capture2](https://user-images.githubusercontent.com/33293951/69727771-1017b600-111b-11ea-9689-fa0c071333e1.PNG)
![Capture](https://user-images.githubusercontent.com/33293951/69727784-13ab3d00-111b-11ea-83f5-b8a1e88feac5.PNG)

**Comment by cormacmchale** [comment]
This placeholder for preserving the volume is also used in the pause logic
