### ISSUE TITLE
Power- ups

### ISSUE THREAD

**Issue by cormacmchale** [cormacmchale/MobileGameProject#13]
Would like to add power ups to make the player faster and shoot faster/ with bigger bullets etc..
again will have to run past the designer..
https://github.com/cormacmchale/MobileGameProject/issues/7

**Comment by Liam-Higgins2018** [comment]
These implementations are a good way to keep game play more interesting.  I give the developer the go ahead to implement these features in the game.

**Comment by cormacmchale** [comment]
Power-ups now not going to be implemented due to time constraints and other due dates for different modules. Maybe will come back to implement after project has been corrected.
Closing for now
