### ISSUE TITLE
Explosion animations

### ISSUE THREAD

**Issue by cormacmchale** [cormacmchale/MobileGameProject#14]
Will possible add animations to play when a bullet collide with an enemy object..
Will make game feel more properly built/developed

**Comment by cormacmchale** [comment]
Again will have to wait for designer to give the go ahead.

**Comment by Liam-Higgins2018** [comment]
I approve of this new design choice

**Comment by cormacmchale** [comment]
An I frame flash animation for the player will also be included.

**Comment by cormacmchale** [comment]
https://www.youtube.com/watch?v=3RyCUSEeAGM
Starting here for an explosion animation

**Comment by cormacmchale** [comment]
Previously mentioned tutorial very good,
Now using this unity answer to put this script on animation
https://answers.unity.com/questions/610673/how-to-destory-a-gameobject-in-c-after-3-seconds.html

**Comment by cormacmchale** [comment]
Explosion is played once and then destroys itself after one animation loop. Problem solved, can add different explosions now if necessary following the same solution.
