### ISSUE TITLE
Android Over-lay

### ISSUE THREAD

**Issue by cormacmchale** [cormacmchale/MobileGameProject#15]
The Design Document wants the player to be able to move by swiping on Android...
However I think it would be much easier to develop a button over-lay with translucent buttons for android... this will be up for consideration for the designer..

**Comment by Liam-Higgins2018** [comment]
I approve of this new design choice.

**Comment by cormacmchale** [comment]
Starting here
https://www.youtube.com/watch?v=kdkrjCF0KCo

**Comment by cormacmchale** [comment]
![Capture](https://user-images.githubusercontent.com/33293951/68587587-531d2c80-047f-11ea-90de-3ffe1754a6e6.PNG)
I think I will have a folder of scripts to handle the button presses, possibly a better way of doing this but will be okay for now

**Comment by cormacmchale** [comment]
Main issue I'm having is trying to register a button being held down.
If I can map a button to the horizontal axis then should be able to use the same movement as before

**Comment by cormacmchale** [comment]
![Capture](https://user-images.githubusercontent.com/33293951/68604290-0bf46300-04a2-11ea-9f1b-381f7857f236.PNG)
![Capture2](https://user-images.githubusercontent.com/33293951/68604292-0dbe2680-04a2-11ea-9cbd-609878f353c5.PNG)
By using the event trigger system along with a boolean I can apply movement on a button down event and then stop it on a button up on the same button. Reasonable solution

**Comment by cormacmchale** [comment]
https://forum.unity.com/threads/simulate-keypress-in-unity.541129/
Seem to get this answer everywhere.. Think for the moment I wont be able to affect the Input.Axis for the smooth movement obtained from the keyboard.

**Comment by cormacmchale** [comment]
Movement fixed and game deployed scaled correctly on android, however with the new movement system... the shooting no longer works, this will need to be fixed
How the over-lay looks now:
![Capture](https://user-images.githubusercontent.com/33293951/68611161-60eba580-04b1-11ea-8f3c-495ab5c05d62.PNG)

**Comment by cormacmchale** [comment]
Shooting can be fixed by allowing access to the shoot method that took an int parameter to set the angle! This was based of the value of input.getAxis() but by setting the angle based of the button press the player will shoot that direction while moving that way. Then reset the angle to -1 when you let your hand off a button to have no shooting without movement. Problem solved
![Capture2](https://user-images.githubusercontent.com/33293951/68612144-c2147880-04b3-11ea-8f9c-20da60e677d3.PNG)
![Capture](https://user-images.githubusercontent.com/33293951/68612155-c6409600-04b3-11ea-84e8-80766627e96e.PNG)

**Comment by cormacmchale** [comment]
This will actually have to be done a different way, will have to add a level of indirection.. will have to get the MoveButton script to pass the angle to a different object to hold for access from the shoot button, otherwise the shootbutton won't know which script to find in start()

**Comment by cormacmchale** [comment]
Using Android Manager as a placeholder for angle now.. workable solution
