### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by cormacmchale** [cormacmchale/MobileGameProject#2]
Must optimize movement for player experience

**Comment by cormacmchale** [comment]
added in basic up down and left right movement for the moment,
I think the best thing to make the player movement fluid would be to have the animation just change the direction of the car to face forward in whatever direction the player was moving... will have to update this when I get the assets.

**Comment by cormacmchale** [comment]
first thing is just to increase speed to a more 'exciting level' make it more enjoyable to move.
![increasespeed](https://user-images.githubusercontent.com/33293951/66392689-82480600-e9c8-11e9-8e44-372b4483b3c0.PNG)
Just increased what's being added to the transforms position by *2.5f
Just a simple temporary solution to get a better feel for what I want in the end product

**Comment by cormacmchale** [comment]
Added a serialize field so I can play around with speed.. but going to leave movement implementation as it is.
![movement](https://user-images.githubusercontent.com/33293951/66663060-e7f2f700-ec41-11e9-9f31-a6a160be0480.PNG)

**Comment by cormacmchale** [comment]
These changes deviate slightly from the design document... will have to get the designer to okay the player to have dynamic movement and go left and right aswell, It will allow for more complex enemy movement patterns..

**Comment by Liam-Higgins2018** [comment]
Yeah I am alright with the changes that are to be implemented
