### ISSUE TITLE
Player Firing

### ISSUE THREAD

**Issue by cormacmchale** [cormacmchale/MobileGameProject#3]
Players needs to be able to fire bullets in every direction

**Comment by cormacmchale** [comment]
I think I will add a script to the player that will spawn bullets on a key press...
to me this makes the most sense design-wise

**Comment by cormacmchale** [comment]
Initially going to have the bullet shoot in the direction the player is moving.. will run this past the dev.
See : https://github.com/cormacmchale/MobileGameProject/issues/7

**Comment by cormacmchale** [comment]
Seems like this could improve Gameplay for the user! Hoping to hear from designer soon...
basic left and right shooting implemented as follows -
![bullet](https://user-images.githubusercontent.com/33293951/66400526-8a5c7180-e9d9-11e9-9a1a-72b9ae6ff999.PNG)

![bulletMovement](https://user-images.githubusercontent.com/33293951/66400641-c7c0ff00-e9d9-11e9-8983-1e5b37d1f840.PNG)

Will have to tidy this function up

**Comment by cormacmchale** [comment]
Found out through research and testing that accessing the quarternion is a very bad idea! It's set and calculated using complex numbers!... accessing the Rotate method on a transform is a better way!!

**Comment by cormacmchale** [comment]
Finished method below... essentially configure an angle based off movement direction, then add rotation accordingly.

![firingscript](https://user-images.githubusercontent.com/33293951/66662620-12908000-ec41-11e9-9143-3b5439083ab6.PNG)

Note: Rotation reset at beginning of method to keep it working correctly. May re-visit this again if time permits.

**Comment by cormacmchale** [comment]
Will wait for go ahead from designer before closing fully!

**Comment by cormacmchale** [comment]
Player now unable to fire while not moving as per design document

**Comment by Liam-Higgins2018** [comment]
I approve of these changes
